number_of_tasks = (12)
number_of_hours = (1.5)
nazvanie_kursa = ('Pyton')
time_of_task = (number_of_hours / number_of_tasks)
print('Курс:',nazvanie_kursa,', всего задач:',number_of_tasks,' , затрачено часов:',number_of_hours,' , среднее время выполнения',time_of_task,'часа.')